version: '3.3'
 
services:
  drupal:
    build: ./php-apache
    ports:
      - 8082:80
    volumes:
      - ./app:/var/www/html:rw,delegated
    restart: always
 
  mariadb:
   image: mariadb:latest
   environment:
    MYSQL_RANDOM_ROOT_PASSWORD: 1
    MYSQL_DATABASE: dev
    MYSQL_USER: dev
    MYSQL_PASSWORD: dev123
   volumes:
    - ./db-data:/var/lib/mysql
   restart: always
   command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
   ports:
    - "3307:3306"
 
volumes:
  app:
  db-data: